server:
  port: ${SERVER_PORT:8080}

ollama:
  base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  model: ${OLLAMA_MODEL:llama3.1}

elasticsearch:
  hostname: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}

embedding:
  provider: ${EMBEDDING_PROVIDER:ollama}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aichatbot}
    username: ${DB_USERNAME:aichatbot}
    password: ${DB_PASSWORD:aichatbot}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8081/realms/ai-chatbot}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:http://localhost:8081/realms/ai-chatbot/protocol/openid-connect/certs}